[package]
name = "dune_data"
version = "0.1.0"
edition = "2024"

[dependencies]
dune_common.workspace = true

anyhow.workspace = true
bytemuck.workspace = true
num_enum.workspace = true
flate2.workspace = true

[build-dependencies]
dune_data_gen.workspace = true